version: "3"
services:
  web:
    build:
      context: ./elixir
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - ./workspace/:/app

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DBNAME=sample_dev
    volumes:
      - ./data:/var/lib/postgresql/data
