GET http://localhost:8000/

###

GET http://localhost:8000/todos

###

GET http://localhost:8000/todos/5dcff277-b58e-41cf-b577-bc150e71e03d

###

POST http://localhost:8000/todos
content-type: application/json

{
    "title": "petting"
}

###

PUT http://localhost:8000/todos/5dcff277-b58e-41cf-b577-bc150e71e03d
content-type: application/json

{
    "done": true
}


###

DELETE http://localhost:8000/todos/<id>
